name: "m152-stat-theory"

project:
  type: website

website:
  navbar:
    title: "Statistical Theory"
    description: |
      Math 152, Statistical Theory, Pomona College
    background: light
    foreground: dark
    search: true
    right:
      - text: "Syllabus"
        href: syllabus.qmd
      - text: "Class Notes"
        href: notes.qmd
      - text: "GitHub"
        href: github.qmd
    logo: images/st47s.png

format:
  html:
    css: styles.css



